# Simplified Supabase Local Development Setup

services:
  db:
    image: postgres:14-alpine
    container_name: supabase_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rest:
    depends_on:
      - db
    image: postgrest/postgrest:v10.1.2
    container_name: supabase_rest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@db:5432/postgres
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long

  auth:
    depends_on:
      - db
    image: supabase/gotrue:v2.23.0
    container_name: supabase_auth
    restart: unless-stopped
    ports:
      - "9999:9999"
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_URI_ALLOW_LIST: http://localhost:3000
      GOTRUE_DISABLE_SIGNUP: "false"
      GOTRUE_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_EXTERNAL_EMAIL_ENABLED: "false"
      GOTRUE_MAILER_AUTOCONFIRM: "true"
      API_EXTERNAL_URL: http://localhost:8000

  storage:
    depends_on:
      - db
      - rest
    image: supabase/storage-api:v0.28.0
    container_name: supabase_storage
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      PGRST_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      REGION: us-east-1
      POSTGREST_URL: http://rest:3000
      FILE_SIZE_LIMIT: 52428800
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /tmp/storage
      TENANT_ID: stub
      GLOBAL_S3_BUCKET: stub

  meta:
    depends_on:
      - db
    image: supabase/postgres-meta:v0.63.0
    container_name: supabase_meta
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: db
      PG_META_DB_PASSWORD: postgres
      PG_META_DB_PORT: 5432
      PG_META_DB_USER: postgres

  inbucket:
    image: inbucket/inbucket:stable
    container_name: supabase_inbucket
    restart: unless-stopped
    ports:
      - "2500:2500" # SMTP
      - "9000:9000" # Web interface
      - "1100:1100" # POP3

volumes:
  postgres_data:
