[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Add your environment variables here
  VITE_STRIPE_PUBLISHABLE_KEY = "pk_test_YOUR_STRIPE_PUBLISHABLE_KEY"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200